version: '3'
services:
  #--------------------------------------------------------------------------------------------# 
  #                                 Qflood                                                     #
  #--------------------------------------------------------------------------------------------#
  qflood:
    container_name: qflood
    image: cr.hotio.dev/hotio/qflood
    network_mode: "container:gluetun"
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
      - FLOOD_AUTH=false
    volumes:
      - $DOCKERDIR/qflood:/config
    labels:
      - flame.type=application # "app" works too
      - flame.name=QFlood
      - flame.url=http://192.168.0.107:3000
      - flame.icon=https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/flood.png
