version: "3"
services:
#--------------------------------------------------------------------------------------------# 
#                                 Prowlarr                                                   #
#--------------------------------------------------------------------------------------------#
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/prowlarr:/config
    ports:
      - $PROWLARR_PORT:9696
    restart: unless-stopped