version: '3.3'
services:
    siyuan:
        volumes:
            - '$DOCKERDIR/siyuan/:/siyuan/workspace'
        ports:
            - '6806:6806'
        image: b3log/siyuan
        restart: unless-stopped
        container_name: siyuan
