version: "3"
services:
  #--------------------------------------------------------------------------------------------# 
  #                                 Watchtower                                                 #
  #--------------------------------------------------------------------------------------------# 
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_CLEANUP=true # Removed dangling images
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_POLL_INTERVAL=43200 #every 12 hours
      - WATCHTOWER_ROLLING_RESTART=true #restarts container as soon as its updated
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL="discord://token@id"
      - WATCHTOWER_NOTIFICATION_TEMPLATE="{{range .}} ({{.Level}}) {{.Message}}{{println}}{{end}}"
