version: '3'
services:
#--------------------------------------------------------------------------------------------# 
#                                 Bazarr                                                     #
#--------------------------------------------------------------------------------------------#
  bazarr:
    container_name: bazarr
    hostname: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "$BAZARR_PORT:6767"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=$UMASK
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/bazarr:/config
      - $MOVIE:/movies
      - $TV_SHOW:/tv
    labels:
      - flame.type=application # "app" works too
      - flame.name=Bazarr
      - flame.url=https://bazarr.DOMIAN.TLD
      - flame.icon=https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/bazarr.png