version: "3"
services:
#--------------------------------------------------------------------------------------------#
#                                FreshRSS                                                    #
#--------------------------------------------------------------------------------------------#
  freshrss-app:
    image: linuxserver/freshrss
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    networks:
      - freshrss
    ports:
      - "$RSS:80"
    depends_on:
      - freshrss-db
    volumes:
    # to be modified depending on your needs
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: $TZ
    labels:
      - flame.type=application # "app" works too
      - flame.name=FreshRSS
      - flame.url=https://rss.DOMAIN
      - flame.icon=https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/freshrss.png

  freshrss-db:
    image: postgres:alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    networks:
      - freshrss
    volumes:
    # to be modified depending on your needs
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: freshrss
      POSTGRES_DB: freshrss
